# Generated by Django 5.0.9 on 2024-10-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.DateTimeField()),
                ('series', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reserved', models.DecimalField(decimal_places=2, max_digits=18)),
                ('available', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=18)),
                ('price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('sum', models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=19)),
            ],
            options={
                'db_table': 'balances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('doc_name', models.CharField(editable=False, max_length=255)),
            ],
            options={
                'db_table': 'documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=55, null=True)),
                ('unit_of_measurement', models.CharField(blank=True, default='шт.', max_length=23, null=True)),
                ('inventory_number', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=55, null=True)),
                ('initial_cost', models.FloatField(blank=True, null=True)),
                ('factory_number', models.CharField(blank=True, max_length=55, null=True)),
                ('asset_class', models.CharField(blank=True, max_length=55, null=True)),
                ('series', models.CharField(blank=True, max_length=50, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('med_user', models.CharField(max_length=50)),
                ('salt', models.CharField(max_length=50)),
                ('hashed_password', models.TextField()),
                ('role', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'med_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'positions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'ranks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResponsiblePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'responsiblePersons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=50, unique=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('manager', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'suppliers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('sum', models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=19)),
                ('source', models.CharField(max_length=20)),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'typesOfDocuments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100)),
                ('for_print', models.CharField(blank=True, max_length=128, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'units',
                'managed': False,
            },
        ),
    ]
